[appenders.async_console]
kind = "async_console"
pattern = "{l} {d(%H:%M:%S.%f)} [{M} #FS#{f}#FE#:{L}] {m}\n"

[[appenders.async_console.filter]]
kind = "threshold"
level = "info"

[appenders.async_file]
kind = "async_file"
output_file_name = "Node.log"
pattern = "{l} {d(%H:%M:%S.%f)} [{M} #FS#{f}#FE#:{L}] {m}\n"
append = false

[root]
level = "error"
appenders = ["async_console", "async_file"]

[loggers."crust"]
level = "debug"
appenders = ["async_file"]
additive = false

[loggers."routing"]
level = "trace"

[loggers."routing_stats"]
level = "trace"

[loggers."safe_vault"]
level = "trace"

